### ISSUE TITLE
search should infinite scroll

### ISSUE THREAD

**Issue by jspear29** [jspear29/electro#3]
#right now search only displays the first N result.  when a user hits the bottom on the search results more should be loaded.

**Comment by mjhayes412** [comment]
I'll take this one.

Right now, the search clears the input element. Kill the clearing or save q somewhere else?

**Comment by jspear29** [comment]
see my changes... limit scroll to events from search bar.

**Comment by jspear29** [comment]
figure out what that magic number is in Crate.react.jsx

**Comment by jspear29** [comment]
why save the search query?  could see it being part of a type ahead.
